# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('opening_datetime', models.DateTimeField(help_text='time after which getting a ticket for this lottery is allowed')),
                ('closing_datetime', models.DateTimeField(help_text='time after which getting a ticket for this lottery is no longer allowed')),
                ('winner_ticket', models.CharField(blank=True, help_text='Serialization of the winner ticket/selection of numbers', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(help_text='Serialization of the ticket/selection of numbers made by the player', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
