# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20151212_2126'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lottery',
            managers=[
            ],
        ),
    ]
